export const APPROVED_CLIENT_NAMES = [
  "Abound",
  "Bang!",
  "Be Present",
  "Bible BFF",
  "Breezy AI",
  "Custom Use",
  "Creed",
  "EverKind",
  "FUELIN",
  "Fireflies AI",
  "Honey Homes",
  "Kaiora",
  "Kalam",
  "Kalo",
  "Marketing for Valid (VLD)",
  "Mia",
  "Musa",
  "Olive App",
  "PayMe",
  "Portola",
  "Prep AI (PAI) / Sprout",
  "Prove It",
  "Purpose",
  "Replit",
  "Roamy",
  "Settlemate",
  "SplitPay",
  "Vibecode",
  "Wayk",
  "Willow Voice",
  "ZumiChat",
  "Coco",
  "Soundmap",
  "SuccessAI",
  "HausLabs",
  "Househunt",
  "Voiced AI",
  "Sorce",
  "TapTap Send (TTS)",
  "Turbo AI (TurboLearn)",
  "Unstuck",
  "Wave AI",
  "Synq",
  "Overcomer",
  "Nora: Therapy & Mental Health",
  "Autoreel",
  "Aragon AI - Valid",
  "Jungle",
  "Starla",
  "Listful",
  "MeAgain",
  "Pepper App",
  "Thea",
  "Julius",
  "FitHub",
  "LoxClub",
  "Trace",
  "Butternut AI",
  "Cal AI - Validated",
  "GuruNanda",
  "Equals",
  "Outlast",
  "Robo Agencies",
  "roi",
  "Roi - The net worth app",
  "Doorlist",
  "Umax",
  "Stompers",
  "Kalshi",
  "Slate"
];
