with source(name) as (
  values
    ('Abound'),
    ('Bang!'),
    ('Be Present'),
    ('Bible BFF'),
    ('Breezy AI'),
    ('Custom Use'),
    ('Creed'),
    ('EverKind'),
    ('FUELIN'),
    ('Fireflies AI'),
    ('Honey Homes'),
    ('Kaiora'),
    ('Kalam'),
    ('Kalo'),
    ('Marketing for Valid (VLD)'),
    ('Mia'),
    ('Musa'),
    ('Olive App'),
    ('PayMe'),
    ('Portola'),
    ('Prep AI (PAI) / Sprout'),
    ('Prove It'),
    ('Purpose'),
    ('Replit'),
    ('Roamy'),
    ('Settlemate'),
    ('SplitPay'),
    ('Vibecode'),
    ('Wayk'),
    ('Willow Voice'),
    ('ZumiChat'),
    ('Coco'),
    ('Soundmap'),
    ('SuccessAI'),
    ('HausLabs'),
    ('Househunt'),
    ('Voiced AI'),
    ('Sorce'),
    ('TapTap Send (TTS)'),
    ('Turbo AI (TurboLearn)'),
    ('Unstuck'),
    ('Wave AI'),
    ('Synq'),
    ('Overcomer'),
    ('Nora: Therapy & Mental Health'),
    ('Autoreel'),
    ('Aragon AI - Valid'),
    ('Jungle'),
    ('Starla'),
    ('Listful'),
    ('MeAgain'),
    ('Pepper App'),
    ('Thea'),
    ('Julius'),
    ('FitHub'),
    ('LoxClub'),
    ('Trace'),
    ('Butternut AI'),
    ('Cal AI - Validated'),
    ('GuruNanda'),
    ('Equals'),
    ('Outlast'),
    ('Robo Agencies'),
    ('roi'),
    ('Roi - The net worth app'),
    ('Doorlist'),
    ('Umax'),
    ('Stompers'),
    ('Kalshi'),
    ('Slate')
),
normalized as (
  select
    name,
    lower(trim(both '-' from regexp_replace(regexp_replace(name, '&', 'and', 'g'), '[^a-zA-Z0-9]+', '-', 'g'))) as slug
  from source
)
insert into public.clients (name, slug)
select name, slug
from normalized
on conflict (slug) do update
set name = excluded.name;
